Improve MQTT discovery
o0shojo0o/PixelIt pull request #168
Opened 2022-05-01 01:49 UTC by pplucky

Improve MQTT discovery by:
- providing a URL to allow "jumping" from HA device to PixelIT GUI;
- providing a new sensor (by default disabled) for Wifi quality.

2022-05-01 09:42 UTC, o0shojo0o requested changes

2022-05-01 09:42 UTC, o0shojo0o commented on src/PixelIt.ino
> +        payload.replace(F("#ICON#"), "wifi");
Here please still use the F macro for the "wifi".

2022-05-01 21:21 UTC, pplucky commented on src/PixelIt.ino
> +        payload.replace(F("#ICON#"), "wifi");
Done now, please check.

2022-05-02 13:16 UTC, o0shojo0o commented on src/PixelIt.ino
> +        payload.replace(F("#ICON#"), "wifi");
Great, thank you. 
So I will gladly take it :)

2022-05-02 13:17 UTC, merged